# Generated by Django 2.2.7 on 2019-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fale',
            field=models.FilePathField(default=1),
            preserve_default=False,
        ),
    ]
