# Generated by Django 2.2.7 on 2019-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20191203_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fale',
            field=models.FileField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
