# Generated by Django 2.2.7 on 2019-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20191203_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fale',
            field=models.FileField(upload_to='game'),
        ),
    ]
