# Generated by Django 2.2.7 on 2019-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_script_fale'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='fale',
            field=models.FileField(default=1, upload_to='game/static/url_script'),
            preserve_default=False,
        ),
    ]
